services:
  backend:
    image: ${DOCKERHUB_USERNAME}/swiftcart-backend:latest
    container_name: swiftcart-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - NODE_ENV=production

  frontend:
    image: ${DOCKERHUB_USERNAME}/swiftcart-frontend:latest
    container_name: swiftcart-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
