services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
